# Generated by Django 5.0 on 2023-12-08 07:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cardquest', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pokemoncard',
            old_name='evolotuion_stage',
            new_name='evolution_stage',
        ),
        migrations.DeleteModel(
            name='Collection',
        ),
    ]
