# Generated by Django 5.0 on 2023-12-08 07:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cardquest', '0002_rename_evolotuion_stage_pokemoncard_evolution_stage_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Trainer',
        ),
    ]
