# Generated by Django 5.0 on 2023-12-08 07:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cardquest', '0005_collection'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trainer',
            name='location',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
