# Generated by Django 5.0 on 2023-12-08 07:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cardquest', '0006_alter_trainer_location'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trainer',
            name='location',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
