# Generated by Django 5.0 on 2023-12-08 07:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cardquest', '0007_alter_trainer_location'),
    ]

    operations = [
        migrations.AddField(
            model_name='collection',
            name='trainers',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='cardquest.trainer'),
        ),
    ]
